[agents]
pm_tool = "claude"
pm_model = ""
scrum_tool = "claude"
scrum_model = ""
analyst_tool = "claude"
analyst_model = ""
be1_tool = "claude"
be1_model = ""
be2_tool = "claude"
be2_model = ""
fe1_tool = "claude"
fe1_model = ""
fe2_tool = "claude"
fe2_model = ""
leader_tool = "claude"
leader_model = ""

[output]
directory = "./clients/aloweb_vn/output"

[timeouts]
claude_code = 600
opencode = 600

[tech_stack]
backend = "PHP , Laravel , MYSQL"
frontend = "Blade"

[project]
name = "Aloweb Vn"
profile = "fullstack"
